title: Hi! I'm Turgay
description: I am currently focusing on game development and software development.
baseurl: ""
url: https://trgysvc.github.io/

# site settings
taglong: I am currently focusing on game development and software development.
tagshort: Jekyll theme

# author settings
author:
  name: Turgay
  email: turgaysavaci@gmail.com
photo: assets/files/photo.jpg
address: Turkey
phone: +90

# social media links
social:
  facebook: trgysvc
  github: trgysvc
  instagram: trgysvc
  linkedin: turgaysavac%C4%B1/
  stackoverflow: 0000000/username
  x: trgysvc

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
